import {test,expect} from '@playwright/test';import AxeBuilder from '@axe-core/playwright';
test.use({serviceWorkers:'block'});const path='/fm/lamine-yamal-fm26/',endpoint='/api/comments/?path='+encodeURIComponent(path),viewer='11111111-1111-4111-8111-111111111111',id='22222222-2222-4222-8222-222222222222';
test('live comment reads expose no visitor identity and writes enforce authentication/origin',async({request})=>{
 const response=await request.get(endpoint);expect(response.status()).toBe(200);expect(response.headers()['cache-control']).toBe('no-store');const data=await response.json();expect(data).toMatchObject({authenticated:false,viewer_id:null});expect(Array.isArray(data.comments)).toBe(true);
 const denied=await request.post('/api/comments/',{headers:{Origin:'https://palmarghe.com'},form:{path,body:'Never stored: anonymous boundary',request_id:crypto.randomUUID()}});expect(denied.status()).toBe(401);
 const foreign=await request.post('/api/comments/',{headers:{Origin:'https://example.invalid'},form:{path,body:'Never stored: origin boundary',request_id:crypto.randomUUID()}});expect(foreign.status()).toBe(403);
});
test('deployed comment UI handles timeout, reload and confirmed retry with controlled responses and no production writes',async({page,request})=>{
 const response=await request.get(endpoint);expect(response.ok()).toBe(true);const actual=await response.json();await page.clock.install();let failRead=true,reads=0,writes=0,posted=false;const keys:string[]=[];
 // Actual deployed HTML/CSS/script; only comment responses below are controlled.
 // Every POST is intercepted before reaching production.
 await page.route('**/api/comments/**',async route=>{if(route.request().method()==='POST'){writes++;const key=route.request().postData()?.match(/name="request_id"\r\n\r\n([0-9a-f-]+)/)?.[1]??'';keys.push(key);if(writes===1)return;posted=true;return route.fulfill({status:200,json:{ok:true,id,viewer_id:viewer,created:false,removed:false}});}reads++;if(failRead)return;return route.fulfill({json:{...actual,authenticated:true,viewer_id:viewer,comments:posted?[...actual.comments,{id,body:'Controlled deployed UI recovery',created_at:'2026-10-07T10:00:00Z',display_name:'Controlled QA fixture',avatar_key:'avatar-01'}]:actual.comments}});});
 await page.goto(path);await expect.poll(()=>reads).toBe(1);await page.clock.fastForward(12001);await expect(page.locator('.comments-status')).toContainText('yüklenemiyor');failRead=false;await page.getByRole('button',{name:'Yorumları yeniden yükle'}).click();await expect(page.locator('.comment-form')).toHaveCount(1);await page.getByLabel('Yorumunuz').fill('Controlled deployed UI recovery');await page.getByRole('button',{name:'Yorum gönder',exact:true}).click();await expect.poll(()=>writes).toBe(1);await page.clock.fastForward(12001);await expect(page.locator('.comment-delivery-status')).toContainText('Sonuç doğrulanamadı');
 for(const width of [390,1440])for(const theme of ['dark','light','aurora']){await page.setViewportSize({width,height:900});await page.evaluate(t=>document.body.dataset.theme=t,theme);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);const axe=await new AxeBuilder({page}).include('.comments-section').analyze();expect(axe.violations.filter(v=>['serious','critical'].includes(v.impact??''))).toEqual([]);}
 await page.reload();await expect(page.getByLabel('Yorumunuz')).toHaveValue('Controlled deployed UI recovery');await page.evaluate(()=>window.dispatchEvent(new Event('online')));expect(writes).toBe(1);await page.getByRole('button',{name:'Gönderimi doğrula',exact:true}).click();await expect(page.locator('.comment-delivery-status')).toContainText('Yorum kaydedildi');await expect(page.locator('.comment').filter({hasText:'Controlled deployed UI recovery'})).toHaveCount(1);expect(writes).toBe(2);expect(keys[0]).toMatch(/^[0-9a-f-]{36}$/);expect(keys[1]).toBe(keys[0]);await expect(page.getByLabel('Yorumunuz')).toHaveValue('');
});
