import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
test.use({serviceWorkers:'block'});
const viewer='00000000-0000-4000-8000-100000000003';
test('deployed search retains results through timeout and invalid data, then reconnects with controlled GET responses',async({page})=>{
 await page.clock.install();let mode='ok',reads=0;
 await page.route('**/api/search/**',async route=>{expect(route.request().method()).toBe('GET');reads++;if(mode==='stall')return;if(mode==='invalid')return route.fulfill({json:{results:null}});return route.fulfill({json:{results:[{slug:'controlled-search-fixture',title:'Controlled search result',type:'article',excerpt:'Intercepted fixture; no publication is created.',cover_url:'/visuals/og-default.webp'}],categories:[]}});});
 await page.goto('/search/?q=controlled&verify=recovery');const root=page.locator('main [data-live-search]'),input=root.locator('input[name=q]'),retry=root.getByRole('button',{name:'Aramayı yeniden dene'});await expect(root.locator('[data-search-result]')).toHaveCount(1);mode='stall';await input.fill('retained query');await page.clock.runFor(250);await expect.poll(()=>reads).toBe(2);await page.clock.fastForward(12001);await expect(retry).toBeVisible();await expect(input).toHaveValue('retained query');await expect(root.locator('[data-search-result]')).toHaveCount(1);
 for(const width of [390,1440])for(const theme of ['dark','light','aurora']){await page.setViewportSize({width,height:900});await page.evaluate(value=>document.body.dataset.theme=value,theme);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);const audit=await new AxeBuilder({page}).include('main').analyze();expect(audit.violations.filter(v=>['serious','critical'].includes(v.impact??''))).toEqual([]);}
 mode='invalid';await retry.click();await page.clock.runFor(10);await expect(retry).toBeVisible();await expect(root.locator('[data-search-result]')).toHaveCount(1);mode='ok';await page.evaluate(()=>window.dispatchEvent(new Event('online')));await page.clock.runFor(10);await expect(retry).toBeHidden();await expect(root.locator('[data-search-result]')).toHaveCount(1);
});
test('deployed profile timeout and acknowledgement require identity with all profile requests intercepted',async({page})=>{
 await page.clock.install();let reads=0,writes=0;
 // Only anonymous deployed HTML is read. The login marker is controlled, and
 // every profile GET/POST is fulfilled or stalled before reaching production.
 await page.route('**/account/?verify=recovery',async route=>{const response=await route.fetch();await route.fulfill({response,body:(await response.text()).replace('<section class="page-content account-content">','<section class="page-content account-content"><input type="hidden" value="logout">')});});
 await page.route('**/api/profile/',async route=>{if(route.request().method()==='GET'){reads++;if(reads===1)return;return route.fulfill({json:{viewer_id:viewer,display_name:'Controlled profile',bio:'Fixture bio',author_slug:'controlled-fixture',avatar_key:'avatar-05',public_profile:false}});}writes++;expect(route.request().postData()).toContain(viewer);if(writes===1)return;if(writes===2)return route.fulfill({json:{ok:true}});return route.fulfill({json:{ok:true,viewer_id:viewer}});});
 await page.goto('/en/account/?verify=recovery');const form=page.locator('.profile-card form'),status=form.locator('[data-profile-status]'),save=form.getByRole('button',{name:'Save profile'}),bio=form.locator('[name=bio]');await expect.poll(()=>reads).toBe(1);await page.clock.fastForward(12001);await expect(status).toContainText('Profile could not load');await expect(save).toBeDisabled();await page.evaluate(()=>window.dispatchEvent(new Event('online')));await expect(save).toBeEnabled();await bio.fill('Retained controlled edit');await save.click();await expect.poll(()=>writes).toBe(1);await page.clock.fastForward(12001);await expect(status).toContainText('save could not be confirmed');await expect(bio).toHaveValue('Retained controlled edit');await expect(save).toBeEnabled();await page.evaluate(()=>window.dispatchEvent(new Event('online')));expect(writes).toBe(1);expect(reads).toBe(2);await save.click();await expect(status).toContainText('save could not be confirmed');await save.click();await expect(status).toContainText('Profile saved');expect(writes).toBe(3);
});
