import {test,expect} from '@playwright/test';import AxeBuilder from '@axe-core/playwright';
test.use({serviceWorkers:'block'});
const origin='http://127.0.0.1:4322',admin='00000000-0000-4000-8000-100000000001',member='00000000-0000-4000-8000-100000000003';
const fixture=async(context:import('@playwright/test').BrowserContext,locale='tr')=>{await context.addCookies([{name:'pg_mock_user',value:admin,url:origin}]);const slug='comment-delivery-'+Date.now();const response=await context.request.post('/api/studio/',{headers:{Origin:origin},form:{entity:'content',title:'Comment recovery fixture',slug,locale,type:'article',status:'published',body:JSON.stringify({type:'doc',content:[{type:'paragraph',content:[{type:'text',text:'Local controlled comment delivery.'}]}]})}});expect(response.ok()).toBe(true);await context.addCookies([{name:'pg_mock_user',value:member,url:origin}]);return (locale==='en'?'/en/':'/')+slug+'/';};
test('comment reads time out, reconnect without duplicate composers and preserve typed text across failed refresh',async({page,context})=>{
 const path=await fixture(context);await page.clock.install();let stalled=true,reads=0;
 await page.route('**/api/comments/**',async route=>{if(route.request().method()!=='GET')return route.continue();reads++;if(stalled)return;return route.continue();});
 await page.goto(path);await expect(page.locator('.comments-list')).toHaveAttribute('aria-busy','true');expect(await page.locator('.comments-list').evaluate(el=>el.getBoundingClientRect().height)).toBeGreaterThanOrEqual(140);
 await expect.poll(()=>reads).toBe(1);await page.clock.fastForward(12001);await expect(page.locator('.comments-status')).toContainText('yüklenemiyor');await expect(page.getByRole('button',{name:'Yorumları yeniden yükle'})).toBeVisible();
 stalled=false;await page.evaluate(()=>window.dispatchEvent(new Event('online')));await expect(page.locator('.comment-form')).toHaveCount(1);await page.getByLabel('Yorumunuz').fill('Connection recovery retains this draft');
 await page.evaluate(()=>window.dispatchEvent(new Event('online')));expect(reads).toBe(2);await expect(page.locator('.comment-form')).toHaveCount(1);
 for(const width of [320,390,1440])for(const theme of ['dark','light','aurora']){await page.setViewportSize({width,height:900});await page.evaluate(t=>document.body.dataset.theme=t,theme);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);const axe=await new AxeBuilder({page}).include('.comments-section').analyze();expect(axe.violations.filter(v=>['serious','critical'].includes(v.impact??''))).toEqual([]);}
 stalled=true;await page.getByRole('button',{name:'Yorumları yenile'}).click();await expect.poll(()=>reads).toBe(3);await page.clock.fastForward(12001);await expect(page.locator('.comments-status')).toContainText('yüklenemiyor');await expect(page.getByLabel('Yorumunuz')).toHaveValue('Connection recovery retains this draft');stalled=false;await page.getByRole('button',{name:'Yorumları yenile'}).click();await expect(page.locator('.comments-status')).toBeHidden();await expect(page.locator('.comment-form')).toHaveCount(1);await expect(page.getByLabel('Yorumunuz')).toHaveValue('Connection recovery retains this draft');
});
test('a committed comment with a lost response safely retries after reload without duplication or automatic writes',async({page,context})=>{
 const path=await fixture(context);await page.clock.install();await page.goto(path);const body='Delivery QA '+Date.now();await page.getByLabel('Yorumunuz').fill(body);
 let writes=0,committed=false,release:()=>void=()=>{};const gate=new Promise<void>(resolve=>release=resolve);
 await page.route('**/api/comments/',async route=>{if(route.request().method()!=='POST')return route.continue();writes++;await route.fetch();committed=true;await gate;await route.abort('failed');});
 await page.getByRole('button',{name:'Yorum gönder',exact:true}).click();await expect.poll(()=>committed).toBe(true);await expect(page.locator('.comment-form')).toHaveAttribute('aria-busy','true');await page.locator('.comment-form').evaluate((form:HTMLFormElement)=>form.requestSubmit());expect(writes).toBe(1);await page.clock.fastForward(12001);release();await expect(page.locator('.comment-delivery-status')).toContainText('Sonuç doğrulanamadı');await expect(page.getByLabel('Yorumunuz')).toHaveValue(body);await expect(page.getByLabel('Yorumunuz')).toHaveAttribute('readonly','');
 await page.unroute('**/api/comments/');await context.addCookies([{name:'pg_mock_user',value:'00000000-0000-4000-8000-100000000002',url:origin}]);const changed=page.waitForResponse(r=>r.url().endsWith('/api/comments/')&&r.request().method()==='POST');await page.getByRole('button',{name:'Gönderimi doğrula'}).click();expect((await changed).status()).toBe(401);await expect(page.locator('.comment-delivery-status')).toContainText('İlk gönderimin sonucu belirsiz');await expect(page.getByLabel('Yorumunuz')).toHaveAttribute('readonly','');await context.addCookies([{name:'pg_mock_user',value:member,url:origin}]);await page.reload();await expect(page.getByLabel('Yorumunuz')).toHaveValue(body);await expect(page.getByRole('button',{name:'Gönderimi doğrula'})).toBeVisible();await page.evaluate(()=>window.dispatchEvent(new Event('online')));expect(writes).toBe(1);
 const response=page.waitForResponse(r=>r.url().endsWith('/api/comments/')&&r.request().method()==='POST');await page.getByRole('button',{name:'Gönderimi doğrula'}).click();expect((await response).status()).toBe(200);await expect(page.locator('.comment-delivery-status')).toContainText('Yorum kaydedildi');await expect(page.getByLabel('Yorumunuz')).toHaveValue('');await expect(page.locator('.comment').filter({hasText:body})).toHaveCount(1);await expect(page.locator('.comment-form')).toHaveCount(1);await page.reload();await expect(page.getByLabel('Yorumunuz')).toHaveValue('');
});
test('parallel same-key requests create one comment and a deleted receipt cannot resurrect it',async({page,context})=>{
 const path=await fixture(context),key=crypto.randomUUID(),body='Parallel local delivery';const send=()=>context.request.post('/api/comments/',{headers:{Origin:origin},form:{path,body,request_id:key}});const responses=await Promise.all([send(),send(),send()]);expect(responses.map(r=>r.status()).sort()).toEqual([200,200,201]);const ids=await Promise.all(responses.map(async r=>(await r.json()).id));expect(new Set(ids).size).toBe(1);
 const changed=await context.request.post('/api/comments/',{headers:{Origin:origin},form:{path,body:'Different input',request_id:key}});expect(changed.status()).toBeGreaterThanOrEqual(400);
 await context.addCookies([{name:'pg_mock_user',value:admin,url:origin}]);const removed=await context.request.post('/api/studio/',{headers:{Origin:origin},form:{entity:'comment',operation:'delete',id:ids[0]}});expect(removed.ok()).toBe(true);await context.addCookies([{name:'pg_mock_user',value:member,url:origin}]);const retry=await send();expect(retry.status()).toBe(200);expect(await retry.json()).toMatchObject({created:false,removed:true,id:null});await page.goto(path);await expect(page.locator('.comment').filter({hasText:body})).toHaveCount(0);
});

test('English errors retain editable rejected input and private uncertain recovery follows only the same member',async({page,context})=>{
 const path=await fixture(context,'en');await page.goto(path);const body='English recovery '+Date.now();await page.getByLabel('Your comment').fill(body);
 let status=403;await page.route('**/api/comments/',route=>route.request().method()==='POST'?route.fulfill({status,body:'Controlled rejection or uncertain server failure'}):route.continue());
 await page.getByRole('button',{name:'Post comment',exact:true}).click();await expect(page.locator('.comment-delivery-status')).toContainText('Comment was rejected');await expect(page.getByLabel('Your comment')).toHaveValue(body);await expect(page.getByLabel('Your comment')).not.toHaveAttribute('readonly','');
 status=503;await page.getByRole('button',{name:'Post comment',exact:true}).click();await expect(page.locator('.comment-delivery-status')).toContainText('could not be confirmed');await expect(page.getByLabel('Your comment')).toHaveValue(body);
 await context.addCookies([{name:'pg_mock_user',value:'00000000-0000-4000-8000-100000000002',url:origin}]);await page.reload();await expect(page.getByLabel('Your comment')).toHaveValue('');await expect(page.getByRole('button',{name:'Post comment',exact:true})).toBeVisible();
 await context.addCookies([{name:'pg_mock_user',value:member,url:origin}]);await page.reload();await expect(page.getByLabel('Your comment')).toHaveValue(body);await page.setViewportSize({width:320,height:844});await page.evaluate(()=>document.body.dataset.theme='aurora');const axe=await new AxeBuilder({page}).include('.comments-section').analyze();expect(axe.violations.filter(v=>['serious','critical'].includes(v.impact??''))).toEqual([]);
 await page.unroute('**/api/comments/');await page.getByRole('button',{name:'Verify submission',exact:true}).click();await expect(page.locator('.comment-delivery-status')).toContainText('Comment posted');await expect(page.locator('.comment').filter({hasText:body})).toHaveCount(1);await expect(page.getByLabel('Your comment')).toHaveValue('');
});

test('an open composer cannot post as a different signed-in account and malformed confirmation retains the delivery key',async({page,context})=>{
 const path=await fixture(context);await page.goto(path);const body='Identity boundary '+Date.now();await page.getByLabel('Yorumunuz').fill(body);await context.addCookies([{name:'pg_mock_user',value:'00000000-0000-4000-8000-100000000002',url:origin}]);const rejected=page.waitForResponse(r=>r.url().endsWith('/api/comments/')&&r.request().method()==='POST');await page.getByRole('button',{name:'Yorum gönder',exact:true}).click();expect((await rejected).status()).toBe(401);await expect(page.locator('.comment-delivery-status')).toContainText('Oturumun sona erdi');const comments=await context.request.get('/api/comments/?path='+encodeURIComponent(path));expect((await comments.json()).comments).toEqual([]);
 await context.addCookies([{name:'pg_mock_user',value:member,url:origin}]);await page.route('**/api/comments/',route=>route.request().method()==='POST'?route.fulfill({status:201,json:{ok:true}}):route.continue());await page.getByRole('button',{name:'Yorum gönder',exact:true}).click();await expect(page.locator('.comment-delivery-status')).toContainText('Sonuç doğrulanamadı');await expect(page.getByLabel('Yorumunuz')).toHaveValue(body);await page.unroute('**/api/comments/');await page.getByRole('button',{name:'Gönderimi doğrula',exact:true}).click();await expect(page.locator('.comment').filter({hasText:body})).toHaveCount(1);
});
