import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
test.use({serviceWorkers:'block'});
test('image inspector supports real image loading, zoom, keyboard, focus restoration and retry',async({page})=>{
 await page.goto('/');await page.evaluate(()=>{const fixture=document.createElement('section');fixture.innerHTML='<a href="/visuals/hero-glass.webp" data-gallery-lightbox data-alt="First source">First image</a><a href="/visuals/og-default.webp" data-gallery-lightbox data-alt="Second source">Second image</a>';document.querySelector('main')!.append(fixture);});await page.addScriptTag({url:'/scripts/gallery-lightbox.js'});
 const dialog=page.locator('[data-gallery-dialog]');const first=page.getByRole('link',{name:'First image',exact:true});await first.click();await expect(dialog).toBeVisible();await expect(dialog.locator('[data-gallery-image]')).toHaveAttribute('alt','First source');await expect.poll(()=>dialog.locator('img').evaluate(e=>(e as HTMLImageElement).naturalWidth)).toBeGreaterThan(0);
 await dialog.getByRole('button',{name:'Yakınlaştır',exact:true}).click();await expect(dialog.locator('img')).toHaveCSS('transform','matrix(1.5, 0, 0, 1.5, 0, 0)');await page.keyboard.press('ArrowRight');await expect(dialog.locator('img')).toHaveAttribute('alt','Second source');await expect(dialog.locator('.gallery-position')).toHaveText('2 / 2');await expect(dialog.locator('img')).toHaveCSS('transform','matrix(1, 0, 0, 1, 0, 0)');
 for(const width of [320,1440])for(const theme of ['dark','light','aurora']){await page.setViewportSize({width,height:844});await page.evaluate(t=>document.body.dataset.theme=t,theme);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);const findings=await new AxeBuilder({page}).include('[data-gallery-dialog]').analyze();expect(findings.violations.filter(v=>['serious','critical'].includes(v.impact??''))).toEqual([]);}
 await page.keyboard.press('Escape');await expect(first).toBeFocused();await first.evaluate(el=>(el as HTMLAnchorElement).href='/visuals/hero-glass.webp?qa-fail=1');await page.route('**/visuals/hero-glass.webp?qa-fail=1',route=>route.abort());await first.click();await expect(dialog.locator('[role=status]')).toContainText('yüklenemedi');await page.unroute('**/visuals/hero-glass.webp?qa-fail=1');await dialog.getByRole('button',{name:'Görseli yeniden yükle',exact:true}).click();await expect(dialog.locator('[role=status]')).toHaveText('');
});

test('native fullscreen and trusted mobile swipe keep gallery position and close state coherent',async({page,context})=>{
 await page.setViewportSize({width:390,height:844});
 const touch=await context.newCDPSession(page);await touch.send('Emulation.setTouchEmulationEnabled',{enabled:true,maxTouchPoints:1});
 await page.goto('/');await page.evaluate(()=>{const fixture=document.createElement('section');fixture.innerHTML='<a href="/visuals/hero-glass.webp" data-gallery-lightbox data-alt="Swipe first">Swipe first</a><a href="/visuals/og-default.webp" data-gallery-lightbox data-alt="Swipe second">Swipe second</a>';document.querySelector('main')!.append(fixture);});await page.addScriptTag({url:'/scripts/gallery-lightbox.js'});
 const dialog=page.locator('[data-gallery-dialog]');await page.getByRole('link',{name:'Swipe first',exact:true}).click();
 const frame=dialog.locator('.gallery-inspector-frame');const bounds=(await frame.boundingBox())!;const x=bounds.x+bounds.width/2,y=bounds.y+bounds.height/2;
 await touch.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:x+70,y}]});await touch.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x-70,y}]});await touch.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
 await expect(dialog.locator('.gallery-position')).toHaveText('2 / 2');await expect(dialog.locator('img')).toHaveAttribute('alt','Swipe second');
 const full=dialog.getByRole('button',{name:'Tam ekran',exact:true});await full.click();await expect.poll(()=>page.evaluate(()=>document.fullscreenElement?.hasAttribute('data-gallery-screen'))).toBe(true);await expect(full).toHaveAttribute('aria-pressed','true');
 const fullAudit=await new AxeBuilder({page}).include('[data-gallery-screen]').analyze();expect(fullAudit.violations.filter(v=>['serious','critical'].includes(v.impact??''))).toEqual([]);
 await full.click();await expect.poll(()=>page.evaluate(()=>document.fullscreenElement===null)).toBe(true);await expect(full).toHaveAttribute('aria-pressed','false');await dialog.getByRole('button',{name:'Önizlemeyi kapat',exact:true}).click();await expect(dialog).not.toBeVisible();await expect(page.getByRole('link',{name:'Swipe first',exact:true})).toBeFocused();
});

test('fullscreen-denied fallback resets its pressed state when closed and reopened',async({page})=>{
 await page.route('**/qa-gallery-fallback/',async route=>route.fulfill({contentType:'text/html; charset=utf-8',headers:{'Permissions-Policy':'fullscreen=()'},body:'<!doctype html><html lang="tr"><head><meta charset="utf-8"></head><body><main><a href="/visuals/hero-glass.webp" data-gallery-lightbox>Fallback image</a></main><script src="/scripts/gallery-lightbox.js"></script></body></html>'}));
 await page.goto('/qa-gallery-fallback/');const trigger=page.getByRole('link',{name:'Fallback image',exact:true});await trigger.click();const dialog=page.locator('[data-gallery-dialog]'),full=dialog.getByRole('button',{name:'Tam ekran',exact:true});await full.click();await expect(dialog).toHaveClass(/is-fullscreen/);await expect(full).toHaveAttribute('aria-pressed','true');await dialog.getByRole('button',{name:'Önizlemeyi kapat',exact:true}).click();await trigger.click();await expect(full).toHaveAttribute('aria-pressed','false');await expect(dialog).not.toHaveClass(/is-fullscreen/);
});
