import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
test.use({serviceWorkers:'block'});
test('image inspector supports real image loading, zoom, keyboard, focus restoration and retry',async({page})=>{
 await page.goto('/');await page.evaluate(()=>{const fixture=document.createElement('section');fixture.innerHTML='<a href="/visuals/hero-glass.webp" data-gallery-lightbox data-alt="First source">First image</a><a href="/visuals/og-default.webp" data-gallery-lightbox data-alt="Second source">Second image</a>';document.querySelector('main')!.append(fixture);});await page.addScriptTag({url:'/scripts/gallery-lightbox.js'});
 const dialog=page.locator('[data-gallery-dialog]');const first=page.getByRole('link',{name:'First image',exact:true});await first.click();await expect(dialog).toBeVisible();await expect(dialog.locator('[data-gallery-image]')).toHaveAttribute('alt','First source');await expect.poll(()=>dialog.locator('img').evaluate(e=>(e as HTMLImageElement).naturalWidth)).toBeGreaterThan(0);
 await dialog.getByRole('button',{name:'Yakınlaştır',exact:true}).click();await expect(dialog.locator('img')).toHaveCSS('transform','matrix(1.5, 0, 0, 1.5, 0, 0)');await page.keyboard.press('ArrowRight');await expect(dialog.locator('img')).toHaveAttribute('alt','Second source');await expect(dialog.locator('.gallery-position')).toHaveText('2 / 2');await expect(dialog.locator('img')).toHaveCSS('transform','matrix(1, 0, 0, 1, 0, 0)');
 for(const width of [320,1440])for(const theme of ['dark','light']){await page.setViewportSize({width,height:844});await page.evaluate(t=>document.body.dataset.theme=t,theme);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);const findings=await new AxeBuilder({page}).include('[data-gallery-dialog]').analyze();expect(findings.violations.filter(v=>['serious','critical'].includes(v.impact??''))).toEqual([]);}
 await page.keyboard.press('Escape');await expect(first).toBeFocused();await first.evaluate(el=>(el as HTMLAnchorElement).href='/visuals/hero-glass.webp?qa-fail=1');await page.route('**/visuals/hero-glass.webp?qa-fail=1',route=>route.abort());await first.click();await expect(dialog.locator('[role=status]')).toContainText('yüklenemedi');await page.unroute('**/visuals/hero-glass.webp?qa-fail=1');await dialog.getByRole('button',{name:'Görseli yeniden yükle',exact:true}).click();await expect(dialog.locator('[role=status]')).toHaveText('');
});
