import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
test.use({serviceWorkers:'block'});
const origin='http://127.0.0.1:4322',member='00000000-0000-4000-8000-100000000003',editor='00000000-0000-4000-8000-100000000002';
const result=(title:string)=>({slug:'recovery-result',title,type:'article',excerpt:'Controlled local search result',cover_url:'/visuals/og-default.webp'});

test('search bounds stalled reads, retains previous results and filters, then recovers without writes',async({page})=>{
 await page.clock.install();let mode='ok',reads=0;
 await page.route('**/api/search/**',async route=>{expect(route.request().method()).toBe('GET');reads++;if(mode==='stall')return;if(mode==='invalid')return route.fulfill({json:{results:{bad:true}}});return route.fulfill({json:{results:[result(mode==='updated'?'Updated result':'Original result')],categories:[]}});});
 await page.goto('/search/?q=initial&type=article');const root=page.locator('main [data-live-search]'),input=root.locator('input[name=q]'),status=root.locator('[data-search-status]'),retry=root.getByRole('button',{name:'Aramayı yeniden dene'});
 await expect(root.locator('[data-search-result] strong')).toHaveText('Original result');
 mode='stall';await input.fill('retained query');await page.clock.runFor(250);await expect.poll(()=>reads).toBe(2);await page.clock.fastForward(12001);
 await expect(status).toContainText('Önceki sonuçlar');await expect(root.locator('[data-search-results]')).not.toHaveAttribute('aria-busy','true');await expect(retry).toBeVisible();await expect(input).toHaveValue('retained query');await expect(root.locator('select[name=type]')).toHaveValue('article');await expect(root.locator('[data-search-result] strong')).toHaveText('Original result');
 for(const width of [320,390,1440])for(const theme of ['dark','light','aurora']){await page.setViewportSize({width,height:900});await page.evaluate(value=>document.body.dataset.theme=value,theme);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);const audit=await new AxeBuilder({page}).include('main').analyze();expect(audit.violations.filter(v=>['serious','critical'].includes(v.impact??''))).toEqual([]);}
 mode='updated';await retry.click();await page.clock.runFor(10);await expect(root.locator('[data-search-result] strong')).toHaveText('Updated result');await expect(retry).toBeHidden();
 mode='invalid';await input.fill('another query');await page.clock.runFor(250);await expect(retry).toBeVisible();await expect(root.locator('[data-search-result] strong')).toHaveText('Updated result');
 mode='ok';await page.evaluate(()=>window.dispatchEvent(new Event('online')));await page.clock.runFor(10);await expect(retry).toBeHidden();await expect(root.locator('[data-search-result] strong')).toHaveText('Original result');const confirmedReads=reads;await page.evaluate(()=>window.dispatchEvent(new Event('online')));await page.clock.runFor(10);expect(reads).toBe(confirmedReads);
});

test('closed English search cancels stale work and never reconnects the hidden dialog',async({page})=>{
 await page.clock.install();let reads=0,mode='stall';
 await page.route('**/api/search/**',async route=>{reads++;if(mode==='stall')return;return route.fulfill({json:{results:[]}});});
 await page.goto('/en/');await page.locator('.head-actions [data-search-trigger]').click();const dialog=page.getByRole('dialog'),status=dialog.locator('[data-search-status]');await expect.poll(()=>reads).toBe(1);await page.clock.fastForward(12001);await expect(status).toContainText('Search is unavailable');await expect(dialog.getByRole('button',{name:'Retry search'})).toBeVisible();await page.keyboard.press('Escape');await expect(dialog).toBeHidden();
 await page.evaluate(()=>window.dispatchEvent(new Event('online')));await page.clock.runFor(10);expect(reads).toBe(1);mode='ok';await page.locator('.head-actions [data-search-trigger]').click();await page.clock.runFor(10);await expect(dialog.getByRole('button',{name:'Retry search'})).toBeHidden();await expect(status).toContainText('No results');expect(reads).toBe(2);
});

test('profile timeout preserves committed input, verifies retry and rejects a changed account before writing',async({page,context})=>{
 await context.addCookies([{name:'pg_mock_user',value:member,url:origin}]);const baseline=await (await context.request.get('/api/profile/')).json();await page.clock.install();let reads=0,writes=0,committed=false;
 await page.addInitScript(()=>{const original=window.fetch.bind(window);let masked=false;window.fetch=async(...args)=>{const response=await original(...args);if(!masked&&String(args[0]).includes('/api/profile/')&&args[1]?.method==='POST'){masked=true;const signal=args[1].signal;const stream=new ReadableStream({start(controller){signal?.addEventListener('abort',()=>controller.error(new DOMException('Aborted','AbortError')),{once:true});}});return new Response(stream,{status:response.status,headers:response.headers});}return response;};});
 await page.route('**/api/profile/',async route=>{if(route.request().method()==='GET'){reads++;if(reads===1)return;return route.continue();}writes++;if(writes===1){const saved=await route.fetch();expect(saved.ok()).toBe(true);committed=true;return route.fulfill({response:saved});}if(writes===3)return route.fulfill({json:{ok:true}});return route.continue();});
 await page.goto('/account/');const form=page.locator('.profile-card form'),status=form.locator('[data-profile-status]'),save=form.getByRole('button',{name:'Profili kaydet'});await expect.poll(()=>reads).toBe(1);await page.clock.fastForward(12001);await expect(status).toContainText('Profil yüklenemedi');await expect(save).toBeDisabled();await page.evaluate(()=>window.dispatchEvent(new Event('online')));await expect(save).toBeEnabled();expect(reads).toBe(2);
 await form.locator('[name=display_name]').fill('Recovery Member');const bio=form.locator('[name=bio]');await bio.fill('Retained timed-out profile edit');await save.click();await expect.poll(()=>committed).toBe(true);await page.clock.fastForward(12001);await expect(status).toContainText('kayıt sonucu doğrulanamadı');await expect(bio).toHaveValue('Retained timed-out profile edit');await expect(save).toBeEnabled();await page.evaluate(()=>window.dispatchEvent(new Event('online')));expect(writes).toBe(1);expect(reads).toBe(2);
 await save.click();await expect(status).toContainText('Profil kaydedildi');expect((await (await context.request.get('/api/profile/')).json()).bio).toBe('Retained timed-out profile edit');await save.click();await expect(status).toContainText('kayıt sonucu doğrulanamadı');await expect(bio).toHaveValue('Retained timed-out profile edit');
 await context.addCookies([{name:'pg_mock_user',value:editor,url:origin}]);const editorBefore=await (await context.request.get('/api/profile/')).json();const rejected=page.waitForResponse(r=>r.url().endsWith('/api/profile/')&&r.request().method()==='POST');await save.click();expect((await rejected).status()).toBe(401);await expect(status).toContainText('Oturumunuz sona erdi');expect(await (await context.request.get('/api/profile/')).json()).toEqual(editorBefore);
 await context.addCookies([{name:'pg_mock_user',value:member,url:origin}]);if(!baseline.display_name)return;const restored=await context.request.post('/api/profile/',{headers:{Origin:origin},form:{viewer_id:member,display_name:baseline.display_name,bio:baseline.bio,avatar_key:baseline.avatar_key,author_slug:baseline.author_slug,...(baseline.public_profile?{public_profile:'on'}:{})}});expect(restored.ok()).toBe(true);
});
