import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
const origin='http://127.0.0.1:4322';
test.beforeEach(async({page,context})=>{await context.addCookies([{name:'pg_mock_user',value:'00000000-0000-4000-8000-100000000001',url:origin}]);await page.clock.setFixedTime(new Date('2040-01-01T00:00:00Z'));});
test('settings show persisted server time despite a wrong browser clock and retain it after failure',async({page})=>{
 await page.goto('/studio/?section=homepage');
 const navigated=page.waitForEvent('framenavigated',frame=>frame===page.mainFrame());const posted=page.waitForResponse(r=>r.url().endsWith('/api/studio/')&&r.request().method()==='POST');await page.getByRole('button',{name:'Ana sayfayı kaydet',exact:true}).click();expect((await posted).status()).toBe(303);await navigated;await page.waitForLoadState('domcontentloaded');
 const time=page.locator('[data-studio-record-time] time');await expect(time).toBeVisible();const stored=await time.getAttribute('datetime');expect(new Date(stored!).getUTCFullYear()).toBe(new Date().getUTCFullYear());await expect(page.locator('[data-studio-record-time]')).toContainText('Türkiye saati');
 const title=page.locator('[name=hero_title_tr]'),original=await title.inputValue();await title.fill(original+' QA');
 await page.route('**/api/studio/',route=>route.request().method()==='POST'?route.fulfill({status:500,body:'Controlled local save failure'}):route.continue());
 await page.getByRole('button',{name:'Ana sayfayı kaydet',exact:true}).click();await expect(page.locator('.studio-settings-status')).toContainText('Sunucu işlemi tamamlayamadı');await expect(time).toHaveAttribute('datetime',stored!);await expect(title).toHaveValue(original+' QA');
 await page.getByRole('button',{name:'Değişiklikleri geri al',exact:true}).click();await expect(title).toHaveValue(original);await page.unroute('**/api/studio/');await page.reload();await expect(time).toHaveAttribute('datetime',stored!);
 for(const width of [390,1440])for(const theme of ['dark','light','aurora']){await page.setViewportSize({width,height:900});await page.evaluate(t=>document.body.dataset.theme=t,theme);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);const axe=await new AxeBuilder({page}).include('[data-studio-record-time]').analyze();expect(axe.violations.filter(v=>['serious','critical'].includes(v.impact??''))).toEqual([]);}
});
test('content save timestamps advance only after a successful transaction and remain after reload',async({page,context})=>{
 const title='Kayıt zamanı QA '+Date.now();const saved=await context.request.post('/api/studio/',{headers:{Origin:origin},form:{entity:'content',title,slug:'saved-time-qa-'+Date.now(),locale:'tr',type:'article',status:'draft',body:JSON.stringify({type:'doc',content:[{type:'paragraph',content:[{type:'text',text:'Controlled local timestamp fixture'}]}]})}});expect(saved.ok()).toBe(true);
 const open=async(navigate=true)=>{if(navigate)await page.goto('/studio/?section=content');await page.locator('.content-list tbody tr').filter({hasText:title}).getByRole('link',{name:'Düzenle',exact:true}).click();await expect(page.locator('[data-studio-record-time] time')).toBeVisible();};await open();
 const time=page.locator('[data-studio-record-time] time'),before=await time.getAttribute('datetime');expect(new Date(before!).getUTCFullYear()).toBe(new Date().getUTCFullYear());await page.locator('[name=excerpt]').fill('Controlled local metadata update');
 await page.route('**/api/studio/',route=>route.request().method()==='POST'?route.fulfill({status:500,body:'Controlled local transaction failure'}):route.continue());
 await page.getByRole('button',{name:'Taslak kaydet',exact:true}).click();await expect(page.locator('[data-editor-save-state]')).toContainText('Sunucu işlemi tamamlayamadı');await expect(time).toHaveAttribute('datetime',before!);
 await page.unroute('**/api/studio/');const posted=page.waitForResponse(r=>r.url().endsWith('/api/studio/')&&r.request().method()==='POST');await page.getByRole('button',{name:'Taslak kaydet',exact:true}).click();expect((await posted).status()).toBe(303);await expect(page).toHaveURL(origin+'/studio/?section=content');await expect(page.locator('.content-list')).toBeVisible();await open(false);const after=await time.getAttribute('datetime');expect(Date.parse(after!)).toBeGreaterThan(Date.parse(before!));expect(new Date(after!).getUTCFullYear()).toBe(new Date().getUTCFullYear());await page.reload();await expect(time).toHaveAttribute('datetime',after!);
});
