import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
const sections=['dashboard','collections','content','categories','tags','media','messages','comments','members','access','appearance','homepage','advertising','traffic','navigation','redirects','audit','health','settings'];
for(const width of [320,768,1440])test('all Studio sections remain bounded and accessible at '+width,async({page,context})=>{
 test.setTimeout(180000);await page.emulateMedia({reducedMotion:'reduce'});await context.addCookies([{name:'pg_mock_user',value:'00000000-0000-4000-8000-100000000001',url:'http://127.0.0.1:4322'}]);await page.setViewportSize({width,height:900});
 for(const section of sections){await page.goto('/studio/?section='+section);if(section==='content')await expect(page.locator('#block-editor')).toBeVisible();else await expect(page.locator('.admin-main h1')).toBeVisible();for(const theme of ['dark','light','aurora']){await page.evaluate(theme=>document.body.dataset.theme=theme,theme);const themeColor=theme==='light'?'rgb(32, 29, 39)':theme==='aurora'?'rgb(245, 241, 232)':'rgb(243, 241, 234)';await expect(page.locator('body')).toHaveCSS('color',themeColor);await expect(page.locator('.studio-home-link')).toHaveCSS('color',themeColor);if(width>900)await expect(page.locator('.admin-side nav a[aria-current=page]')).toHaveCSS('color',themeColor);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth),section+' '+theme).toBe(true);if(width===320){for(const action of await page.locator('.admin-record-table .record-action a,.admin-record-table .record-action button').all()){const box=await action.boundingBox();expect(box?.x).toBeGreaterThanOrEqual(0);expect((box?.x??0)+(box?.width??0)).toBeLessThanOrEqual(width);expect(box?.height).toBeGreaterThanOrEqual(44);}}const audit=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21a','wcag21aa','wcag22a','wcag22aa']).analyze();expect(audit.violations.filter(v=>['serious','critical'].includes(v.impact??'')).map(v=>({id:v.id,targets:v.nodes.map(n=>({target:n.target,html:n.html,checks:n.any.map(check=>check.data)}))})),section+' '+theme).toEqual([]);}}
});

test('populated content records keep edit, preview and confirmation targets reachable without publishing',async({page,context})=>{
 test.setTimeout(60000);const origin='http://127.0.0.1:4322';await context.addCookies([{name:'pg_mock_user',value:'00000000-0000-4000-8000-100000000001',url:origin}]);await page.emulateMedia({reducedMotion:'reduce'});
 const title='Responsive action QA '+Date.now();const saved=await context.request.post('/api/studio/',{headers:{Origin:origin},form:{entity:'content',title,slug:'responsive-action-'+Date.now(),locale:'tr',type:'article',status:'draft',body:JSON.stringify({type:'doc',content:[{type:'paragraph',content:[{type:'text',text:'Local draft-only action layout fixture.'}]}]})}});expect(saved.ok()).toBe(true);
 await page.goto('/studio/?section=content');const row=page.locator('.content-list tbody tr').filter({hasText:title});const href=await row.getByRole('link',{name:'Düzenle',exact:true}).getAttribute('href');const id=new URL(href!,origin).searchParams.get('edit');expect(id).toBeTruthy();
 try{for(const width of [320,768,1440]){await page.setViewportSize({width,height:900});for(const theme of ['dark','light','aurora']){await page.evaluate(theme=>document.body.dataset.theme=theme,theme);for(const action of await row.locator('a,summary').all()){const rect=await action.boundingBox();expect(rect?.height).toBeGreaterThanOrEqual(44);if(width===320)expect((rect?.x??0)+(rect?.width??0)).toBeLessThanOrEqual(await page.evaluate(()=>document.documentElement.clientWidth));}await row.locator('summary').click();const confirmation=row.getByRole('button',{name:'Silmeyi onayla',exact:true});await expect(confirmation).toBeVisible();if(width===320){const rect=await confirmation.boundingBox();expect((rect?.x??0)+(rect?.width??0)).toBeLessThanOrEqual(await page.evaluate(()=>document.documentElement.clientWidth));}await row.locator('summary').click();const audit=await new AxeBuilder({page}).include('.content-list').withTags(['wcag2a','wcag2aa','wcag21a','wcag21aa','wcag22a','wcag22aa']).analyze();expect(audit.violations.filter(v=>['serious','critical'].includes(v.impact??''))).toEqual([]);}}}
 finally{expect((await context.request.post('/api/studio/',{headers:{Origin:origin},form:{entity:'content',operation:'delete',id:id!}})).ok()).toBe(true);}
});
